### PR TITLE
fix: merge default's merge_vars into global_merge_vars

### PR DESCRIPTION
**Pull request by kennethkalmer**
The code and the documentation was out of sync here, and resulted in an exception when using merge_vars in the defaults.

### CODE REVIEW

**Comment by kennethkalmer** [comment]
I also want to suggest a slight change in behavior with regards to defaults, which imho makes more sense.

Instead of [these two lines][1] acting with `||` operations, should the hashes not be merged together in the correct order? I haven't written tests, but my feeling is the behavior is not what I expect.

I'd expect roughly the following:

```ruby
default = { foo: :bar, baz: :quix }
this_mail = { foo: :nobar }
# Merge
result #=> { foo: :nobar, baz: :quix }
```

I'd gladly make these changes if you'd like.

1. https://github.com/renz45/mandrill_mailer/blob/master/lib/mandrill_mailer/arg_formatter.rb#L102-L103

**Comment by renz45** [comment]
Thanks for the pull request :) I'll release a patched version momentarily.

As for the defaults, its hard to say. The original use case for the defaults was to have something as a value if it was never set to begin with. Merge vars are a bit different since you could consider each value to be separate default values.

I'd be ok with merging those if you wanted to make the changes :) :+1:

**Comment by kennethkalmer** [comment]
Only a pleasure!

I'll take a stab at merging up the different layers over the next few days, let me start pumping out more mails through this gem to get a feel for how it should work.

**Comment by kennethkalmer** [comment]
Hey @renz45, it seems you only closed the PR and never merged it! I caught this by switching my Gemfile entry back to 1.0.2...

Thanks!

**Comment by renz45** [comment]
That was dumb of me.... D: I merged your branch manually, and bumped the version again so I could release it. Sorry about that.

**Comment by kennethkalmer** [comment]
No sweat, thanks for getting it in!

**Pull request closed without merging**
