### PR TITLE
use proper defaults in ArgFormatter

### PR DESCRIPTION
**Pull request by etipton**
The defaults I was setting (from, from_name) weren't being utilized in the API call

### CODE REVIEW

**Comment by renz45** [comment]
Hi etipton, I will confess, I was a bit lazy on the tests for this method. I'm going to add a few to cover defaults a bit better and see what shakes out. You're PR looks good but I'm not sure it fixes your issue without adding a few more tests. :)

**Comment by renz45** [comment]
On second thought, I see the issue, your PR does fix it :) I'll still add the tests. I'll release an updated version shortly. Thanks for catching this!

**Comment by renz45** [comment]
Patch released, thanks again!

**Comment by etipton** [comment]
Awesome, thanks for the quick review and merge!

**Pull request merged**
